name: kutuphane_mobil_d
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    assets:     
    - assets/images/lake.jpg
  get: ^4.6.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  focused_menu: ^1.0.5
  image_picker: ^1.0.2
  bottom_picker: ^2.0.4
  flutter_datetime_picker_plus: ^2.0.1
  intl: ^0.18.1
  circular_menu: ^2.0.1
  flutter_barcode_scanner: ^2.0.0  
  google_mlkit_text_recognition: ^0.10.0
  print_bluetooth_thermal: ^1.0.9
  esc_pos_utils: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
